### PR TITLE
fix(qwant): safe search is now using cookie at qwant

### LINKED ISSUE #47: Does not add safe search on Qwant.
Hello,
Apparently the safe search does not work on Qwant search engine.

In line 4: applicationState is not defined.
https://github.com/serv-inc/safe-search/blob/1973f4cc2307bff284bd02819c43e943738e137b/addon/qwant_safe.js

### PR DESCRIPTION
**Pull request by trollepierre**
fix #47

### CODE REVIEW

**Comment by serv-inc** [comment]
Thanks so much!

Just to validate: qwant safe search was still enabled for me with the addon, despite the error message you mentioned. Did it still work for you ?

This code was a fallback for when the normal process in 

https://github.com/serv-inc/safe-search/blob/master/addon/background.js#L73

would not work. To set a cookie, you could use code similar to https://github.com/serv-inc/safe-search/blob/master/addon/background.js#L147 . Then, this file could be completely removed .

**Comment by trollepierre** [comment]
Hello,
> Just to validate: qwant safe search was still enabled for me with the addon, despite the error message you mentioned. Did it still work for you ?

**Comment by trollepierre** [comment]
So I am a bit confused. I guess the file, I edited, can  be removed, then?

**Comment by serv-inc** [comment]
Exactly, and its functionality moved to background.js.

Pierre ***@***.***> schrieb am Di., 19. März 2024, 11:21:

**Comment by trollepierre** [comment]
then, I rewrite the change into a new MR: https://github.com/serv-inc/safe-search/pull/49

**Pull request closed without merging**
